## New Make system
## ---------------
##
##   > make -s [DEBUG=0] [all|check|install|clean]
##
## ** ALWAYS USE THE `-s` OPTION, UNLESS YOU WANT VERBOSE OUTPUT **


# Variables that may be set on the command line (or as environment variables).
# For example, to perform a release build: > make DEBUG=0 -s
# See mk/gcc.mk for the default flavour, which sets up debug/release builds.
#
# DEBUG=0 - optimised build without debug symbols
#
#     Build directory is $(BUILDDIR)-debug/ (usually build-debug/).
#     $(CFLAGS.DEBUG) added to compile/link.
#
# DEBUG=1 [default] - debug build with basic optimisation
#
#     Build directory is $(BUILDDIR)/ (usually build/).
#     $(CFLAGS.NDEBUG) added to compile/link.
#
# FLAVOUR=<flavour>
#
#     Build directory is $(BUILDDIR)-<flavour>/ (e.g. build-clang/)
#     mk/<flavour>.mk is loaded instead of mk/gcc.mk


# Base config generated by autoconf.
#     (Ignore debug/release flags set by autoconf, as these are selected at build
#     time, rather than requiring a reconfiguration.)
#     Force some important variables to be early bound.
include config.mk
CPPDEFINES := $(patsubst -D%,%,$(DEFS))
CFLAGS     := $(filter-out -g% -O% -Wall -Wextra -Werror,$(CFLAGS))
LDFLAGS    := $(LDFLAGS)
LDLIBS     := $(filter-out -lpthread,$(LIBS)) # pthread is not a library!
LIBS       :=


# Set root of directory name for generated files.
#     Debug builds append -debug
#     Flavour builds append -<flavour>
BUILDDIR := build


# Define functions, and initialise variables.
include mk/main.mk


# Load configuration of all units to be built.
include doc/ALL.mk
include etc/ALL.mk
include src/ALL.mk
include testsuite/ALL.mk
INSTALL_HEADERS := $(wildcard slurm/*.h)


# Create build rules.
include mk/rules.mk
