_subdirs := \
  accounting_storage \
  acct_gather_energy \
  acct_gather_filesystem \
  acct_gather_interconnect \
  acct_gather_profile \
  auth \
  burst_buffer \
  certgen \
  certmgr \
  cgroup \
  cli_filter \
  cred \
  data_parser \
  gpu \
  gres \
  hash \
  http_parser \
  jobacct_gather \
  jobcomp \
  job_submit \
  mcs \
  metrics \
  mpi \
  namespace \
  node_features \
  preempt \
  prep \
  priority \
  proctrack \
  sched \
  select \
  serializer \
  site_factor \
  switch \
  task \
  tls \
  topology \

include $(foreach D,$(_subdirs),$(Here)/$(D)/ALL.mk)
