LIB += common

common.CPPDEFINES := SBINDIR=\"$(sbindir)\"
common.LDLIBS := $(libselinux_LIBS)

common.CFILES := $(call FileList,\
	assoc_mgr.c				\
	bitstring.c				\
	callerid.c				\
	cbuf.c					\
	core_array.c				\
	cpu_frequency.c				\
	cron.c					\
	daemonize.c				\
	data.c					\
	dynamic_plugin_data.c			\
	eio.c					\
	env.c					\
	extra_constraints.c			\
	events.c				\
	fd.c					\
	fetch_config.c				\
	forward.c				\
	global_defaults.c			\
	group_cache.c				\
	half_duplex.c				\
	hostlist.c				\
	http.c					\
	http_con.c				\
	http_mime.c				\
	http_router.c				\
	http_switch.c				\
	identity.c				\
	id_util.c				\
	io_hdr.c				\
	job_features.c				\
	job_options.c				\
	job_record.c				\
	job_resources.c				\
	job_state_reason.c			\
	list.c					\
	log.c					\
	msg_type.c				\
	net.c					\
	node_conf.c				\
	node_features.c				\
	oci_config.c				\
	openapi.c				\
	optz.c					\
	pack.c					\
	parse_config.c				\
	parse_time.c				\
	parse_value.c				\
	part_record.c				\
	persist_conn.c				\
	plugin.c				\
	plugrack.c				\
	port_mgr.c				\
	print_fields.c				\
	probes.c				\
	proc_args.c				\
	read_config.c				\
	reverse_tree.c				\
	run_command.c				\
	run_in_daemon.c				\
	sack_api.c				\
	setproctitle.c				\
	sluid.c					\
	slurm_errno.c				\
	slurm_opt.c				\
	slurm_protocol_api.c			\
	slurm_protocol_defs.c			\
	slurm_protocol_pack.c			\
	slurm_protocol_util.c			\
	slurm_protocol_socket.c			\
	slurm_resolv.c				\
	slurm_resource_info.c			\
	slurm_rlimits_info.c			\
	slurm_step_layout.c			\
	slurm_time.c				\
	slurmdb_defs.c				\
	slurmdb_pack.c				\
	slurmdbd_defs.c				\
	slurmdbd_pack.c				\
	spank.c					\
	state_save.c				\
	stepd_api.c				\
	stepd_proxy.c				\
	strlcpy.c				\
	strnatcmp.c				\
	threadpool.c				\
	timers.c				\
	track_script.c				\
	tres_bind.c				\
	tres_frequency.c			\
	uid.c					\
	util-net.c				\
	working_cluster.c			\
	write_labelled_message.c		\
	x11_util.c				\
	xassert.c				\
	xahash.c				\
	xhash.c					\
	xmalloc.c				\
	xrandom.c				\
	xregex.c				\
	xsched.c				\
	xsystemd.c				\
	xsignal.c				\
	xstring.c				\
)

# ?? It would make more sense to have configure generate this file from
# global_defaults.c.in
$(Here)/global_defaults.c : config.h config.mk
	@echo "CREATE > $@"
	@( echo "/* This file autogenerated by src/common/ALL.mk */"; \
	   echo "char *default_plugin_path = \"$(pkglibdir)\";"; \
	   echo \
	   "char *default_slurm_config_file = \"$(sysconfdir)/slurm.conf\";"; \
	 ) > $@

CLEANFILES += $(Here)/global_defaults.c
